version: '3.9'
services:

  wordpress:
    image: wordpress:5-fpm
    container_name: ${WORDPRESS_CONTAINER_NAME}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  database:
    image: mysql:8
    container_name: ${MYSQL_CONTAINER_NAME}
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    image: nginx:1
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${NGINX_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  adminer:
    image: adminer:4
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "9001:8080"

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: ${FTP_CONTAINER_NAME}
    ports:
      - "21:21"
      - "30000:30000"
    volumes:
      - ${FTP_DIRECTORIO_RAIZ}:/var/www/html
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "${FTP_IP}"
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
    restart: always

networks:
  default:
    external:
      name: proxy001_default